name = "RayTracing"
uuid = "3007c720-8091-40db-9339-e09e4eb4c7ea"
authors = ["Ramiro Vignolo <ramirovignolo@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
