
"""
    Forward
    Backward

Direction types for track traversal.

- `Forward`: Traverse track from entry point to exit point
- `Backward`: Traverse track from exit point to entry point
"""
@enum DirectionType begin
    Forward
    Backward
end

"""
    Track{T<:Real}

Represents a neutron ray trajectory in a 2D domain for transport calculations.

Each track follows a straight-line path at azimuthal angle `ϕ`, entering at point `p` and
exiting at point `q`, with total length `ℓ`. The track is discretized into `segments` for
finite element calculations.

## Key Fields
- `p`, `q`: Entry and exit points of the trajectory
- `ϕ`: Azimuthal angle in radians
- `ℓ`: Total track length
- `bc_fwd`, `bc_bwd`: Boundary conditions at the forward and backward ends
- `dir_next_track_fwd`, `dir_next_track_bwd`: Directions used when following connected tracks
- `segments`: Discretized segments for numerical integration
- `next_track_fwd`, `next_track_bwd`: Connected tracks forming cyclic trajectories
- `ABC`: Line equation coefficients (Ax + By + C = 0)

## Usage
Tracks are generated by `TrackGenerator` and form closed loops through boundary reflections,
enabling iterative transport sweeps across the domain.
"""
mutable struct Track{T<:Real}
    uid::Int
    azim_idx::Int
    track_idx::Int

    p::Point2D{T}
    q::Point2D{T}

    ϕ::T
    ℓ::T

    ABC::SVector{3,T}
    segments::Vector{Segment{T}}

    bc_fwd::BoundaryType
    bc_bwd::BoundaryType
    dir_next_track_fwd::DirectionType
    dir_next_track_bwd::DirectionType

    next_track_fwd::Track{T}
    next_track_bwd::Track{T}

    function Track(
        uid::Int,
        azim_idx::Int,
        track_idx::Int,
        bc_fwd::BoundaryType,
        bc_bwd::BoundaryType,
        dir_next_track_fwd::DirectionType,
        dir_next_track_bwd::DirectionType,
        p::Point2D{T},
        q::Point2D{T},
        ϕ::T,
        ℓ::T,
        ABC::SVector{3,T},
        segments::Vector{Segment{T}}
    ) where {T}
        track = new{T}(
            uid, azim_idx, track_idx, p, q, ϕ, ℓ, ABC, segments,
            bc_fwd, bc_bwd, dir_next_track_fwd, dir_next_track_bwd
        )
        track.next_track_fwd = track
        track.next_track_bwd = track
        return track
    end
end

"""
    universal_id(track::Track) -> Int

Return the globally unique track identifier assigned by [`trace!`](@ref).
"""
universal_id(track::Track) = track.uid

azim_idx(track::Track) = track.azim_idx
track_idx(track::Track) = track.track_idx

"""
    bc_fwd(track::Track) -> BoundaryType

Return the boundary condition encountered when traversing `track` from `p` to `q`.
"""
bc_fwd(track::Track) = track.bc_fwd

"""
    bc_bwd(track::Track) -> BoundaryType

Return the boundary condition encountered when traversing `track` from `q` to `p`.
"""
bc_bwd(track::Track) = track.bc_bwd

"""
    dir_next_track_fwd(track::Track) -> DirectionType

Return the direction used on `track.next_track_fwd` after a forward boundary crossing.
"""
dir_next_track_fwd(track::Track) = track.dir_next_track_fwd

"""
    dir_next_track_bwd(track::Track) -> DirectionType

Return the direction used on `track.next_track_bwd` after a backward boundary crossing.
"""
dir_next_track_bwd(track::Track) = track.dir_next_track_bwd

function show(io::IO, track::Track)
    @unpack ϕ, p, q, ℓ, segments = track
    # println(io, typeof(t))
    println(io, "  Azimuthal angle: ", round(rad2deg(ϕ), digits=2))
    println(io, "  Entry point: ", p)
    println(io, "  Exit point: ", q)
    println(io, "  Length: ", ℓ)
    println(io, "  # of segments: ", length(segments)) # Run segmentize! if this is zero.
    println(io, "  Boundary fwd: ", bc_fwd(track))
    print(io, "  Boundary bwd: ", bc_bwd(track))
    # Avoid printing circular references from cyclic ray tracing.
    # println(io, "  Next track fwd: ", next_track_fwd)
    # print(io,   "  Next track fwd: ", next_track_bwd)
end

# Keep a hard iteration cap while track segmentation edge cases are still being refined.
const MAX_ITER = 10_000

function _segmentize_track!(t, track::Track, k::Int, rtol::Real) # `t` is a TrackGenerator.
    @unpack mesh, tiny_step = t
    @unpack ϕ, segments = track

    # Clear any existing segments before recomputing them.
    empty!(segments)

    # Move a tiny step along ϕ to enter the mesh interior.
    xp = advance_step(track.p, tiny_step, ϕ)

    i = 0
    element = -1
    prev_element = -1
    while i < MAX_ITER

        # Find the element containing `xp`.
        element = find_element(mesh, xp)

        # `xp` may lie on the mesh boundary.
        if on_boundary(mesh, xp, tiny_step)
            if isempty(segments)
                # If segmentation just started, move a tiny step forward.
                xp = advance_step(xp, tiny_step, ϕ)
                continue
            else
                # Otherwise, segmentation has reached the boundary and is done.
                break
            end
        end

        # If `find_element` fails inside the domain, a deformed mesh may require a wider
        # nearest-neighbor search.
        if isequal(element, -1)
            element = find_element(mesh, xp, k)
            if isequal(element, -1)
                error("Try increasing `k`. If the problem persists, raise an issue, this " *
                      "might be a case that hasn't been presented before.")
            end
        end

        # Step forward if the new element matches the previous one.
        if isequal(prev_element, element)
            xp = advance_step(xp, tiny_step, ϕ)
            continue
        end

        # Compute intersections between the track and the element.
        p, q = intersections(mesh, element, track)

        # A vertex hit can produce a zero-length segment; skip it and move forward.
        if isapprox(p, q)
            xp = advance_step(xp, tiny_step, ϕ)
            continue
        end

        segment = Segment(p, q, element)
        push!(segments, segment)

        # Update the next starting point and previous element.
        xp = advance_step(q, tiny_step, ϕ)
        prev_element = element

        i += 1 # Safety counter.
    end

    if !isapprox(track.ℓ, sum(ℓ.(track.segments)); rtol=rtol)
        error("Track with `uid` $(string(track.uid)) has a length that do not match the " *
              "sum of its segments lengths with the provided tolerance `rtol`. Check " *
              "whether this is an actual error or increase `rtol`.")
    end

    return nothing
end
