name: CI
on:
  - push
  - pull_request
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.5'
        os:
          - ubuntu-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: actions/cache@v1
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - run: sudo apt-get install libglu1
      - run: |
          curl -OL http://gmsh.info/bin/Linux/gmsh-4.7.1-Linux64-sdk.tgz
          tar xfv gmsh-4.4.1-Linux64-sdk.tgz
          GMSHROOT=`pwd`/gmsh-4.7.1-Linux64-sdk
          echo "GMSHROOT=${GMSHROOT}" >> $GITHUB_ENV
      - run: |
          echo $GMSHROOT
          $GMSHROOT/bin/gmsh --version
          head $GMSHROOT/lib/gmsh.jl
      - name: install GridapGmsh
        run: |
          julia --project=@. -e 'using Pkg; Pkg.add(PackageSpec(url="https://github.com/gridap/GridapGmsh.jl"))'
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
